name: CI/CD Pipeline

on:
  push:
    branches:
      - main       # For production Build X (Smoke, Feature, Regression)
      - feature/*  # For dev or feature builds, e.g., Build Y
  schedule:
    - cron: "0 0 * * *"  # Nightly regression tests (run every night at midnight UTC)

jobs:
  # Step 1: Run for main (production) or feature (dev) builds
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest --maxfail=5 --disable-warnings -q

  # Step 2: Deployment or test after feature branch push (Build Y)
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/feature/*'  # Only run for feature builds like Build Y

    steps:
    - name: Deploy to Staging
      run: |
        ./deploy.sh  # Script to deploy the app to staging

  # Step 3: Smoke Test after Build Y (Feature Branch)
  smoke_test:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/feature/*'  # Only run after Build Y (feature branches)

    steps:
    - name: Run Smoke Tests
      run: |
        pytest tests/smoke_tests.py --maxfail=3 --disable-warnings -q  # Run smoke tests

  # Step 4: Feature Tests after Build Y (Feature Branch)
  feature_test:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/feature/*'  # Only run after Build Y (feature branches)

    steps:
    - name: Run Feature Tests
      run: |
        pytest tests/feature_tests.py --maxfail=5 --disable-warnings -q  # Run feature tests

  # Step 5: Regression Tests (Nightly Cron)
  regression_test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'schedule'  # Only run on scheduled cron jobs

    steps:
    - name: Run Regression Tests
      run: |
        pytest tests/regression_tests.py --maxfail=10 --disable-warnings -q  # Run regression tests

