# .github/workflows/ci.yml

name: CI Test Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  smoke:
    name: Run Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Smoke Tests
        run: pytest tests/smoke/
